from elements.coils import Coil, RealCoil, RectangularCoil
from elements.helmholtz_pair import HelmholtzPair
from elements.polariser import Polariser

from experiments.mieze.parameters import R_HSF, I_hsf1, HelmholtzSpinFlipper_position_HSF1, startpoint, beamend, step_x

plot_parameters = {
    'coil_simple_1d_x': {
        'element': Coil,
        'plot_dimension': '1d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.5, 'x_end': 0.5, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.0, 'z_end': 0.0},
        'coil_args': None,
    },
    'coil_simple_2d_xy': {
        'element': Coil,
        'plot_dimension': '2d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.2, 'y_end': 0.2, 'z_start': -0.0, 'z_end': 0.0,
                      'rho': 0.2, 'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_simple_2d_yz': {
        'element': Coil,
        'plot_dimension': '2d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.0, 'x_end': 0.0, 'y_start': -0.2, 'y_end': 0.2, 'z_start': -0.2, 'z_end': 0.2,
                      'rho': 0.2, 'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_simple_3d_xz_plane': {
        'element': Coil,
        'plot_dimension': '3d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.2, 'z_end': 0.2,
                      'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_simple_3d_beamline': {
        'element': Coil,
        'plot_dimension': '3d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.0, 'z_end': 0.0,
                      'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_real_2d_xy': {
        'element': RealCoil,
        'plot_dimension': '2d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.2, 'y_end': 0.2, 'z_start': -0.0, 'z_end': 0.0,
                      'rho': 0.2, 'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_square_1d_x': {
        'element': RectangularCoil,
        'plot_dimension': '1d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.0, 'z_end': 0.0},
        'coil_args': None,
    },
    'coil_square_2d_yz': {
        'element': RectangularCoil,
        'plot_dimension': '2d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.0, 'x_end': 0.0, 'y_start': -0.2, 'y_end': 0.2, 'z_start': -0.2, 'z_end': 0.2,
                      'rho': 0.2, 'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_square_2d_xy': {
        'element': RectangularCoil,
        'plot_dimension': '2d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.2, 'y_end': 0.2, 'z_start': -0.0, 'z_end': 0.0,
                      'rho': 0.2, 'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_square_3d': {
        'element': RectangularCoil,
        'plot_dimension': '3d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.2, 'x_end': 0.2, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.2, 'z_end': 0.2,
                      'zoom_factor': 1},
        'coil_args': None,
    },
    'coil_square_3d_beamline': {
        'element': RectangularCoil,
        'plot_dimension': '3d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': -0.0, 'x_end': 0.0, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.2, 'z_end': 0.2,
                      'zoom_factor': 1},
        'coil_args': None,
    },
    'polariser_1d_x': {
        'element_kwargs': {'element_class': Polariser, 'position': (0, 0, 0), 'r_eff': 1, 'current': -1,
                           'length': 0.2, 'windings': 1, 'coil_type': Coil},
        'plot_dimension': '1d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
        'grid_size': {'x_start': 0, 'x_end': 1, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.0, 'z_end': 0.0},
        'coil_args': None,
    },
    'helmholtz_1d_x': {
        'coil_args': None,
        'element_kwargs': {'coil_type': Coil,
                           'current': I_hsf1,
                           'element_class': HelmholtzPair,
                           'position': (HelmholtzSpinFlipper_position_HSF1, 0, 0),
                           'radius': R_HSF
                           },
        'increment': HelmholtzSpinFlipper_position_HSF1/100,
        'grid_size': {'x_start': 0, 'x_end': 3 * HelmholtzSpinFlipper_position_HSF1, 'y_start': -0.0, 'y_end': 0.0, 'z_start': -0.0, 'z_end': 0.0},
        'plot_dimension': '1d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
    },
    'neutron_beam_axis': {
        'coil_args': None,
        'element_kwargs': {'coil_type': Coil,
                           'current': I_hsf1,
                           'element_class': HelmholtzPair,
                           'position': (HelmholtzSpinFlipper_position_HSF1, 0, 0),
                           'radius': R_HSF
                           },
        'grid_size': {'x_start': startpoint, 'x_end': beamend, 'x_step': step_x,
                      'y_start': -0.0, 'y_end': 0.0,
                      'z_start': -0.0, 'z_end': 0.0,
                      'yz_step': (1.0 - -1.0) / 20},
        'plot_dimension': '1d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
    },
    'neutron_beam': {
        'coil_args': None,
        'element_kwargs': {'coil_type': Coil,
                           'current': I_hsf1,
                           'element_class': HelmholtzPair,
                           'position': (HelmholtzSpinFlipper_position_HSF1, 0, 0),
                           'radius': R_HSF
                           },
        'grid_size': {'x_start': startpoint, 'x_end': beamend, 'x_step': step_x,
                      'y_start': -1.0, 'y_end': 1.0,
                      'z_start': -1.0, 'z_end': 1.0,
                      'yz_step': (1.0 - -1.0) / 20},
        'plot_dimension': '1d',
        'plot_args': {'type': 'scalar', 'component': 'x'},
    }
}
